
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author James Snee
 */
public class SetProxyGUI extends javax.swing.JFrame {
    
    

    public JButton getProxyToggleButton() {
        return proxyToggleButton;
    }

    public void setProxyToggleButton(JButton proxyToggleButton) {
        this.proxyToggleButton = proxyToggleButton;
    }
    
    /**
     * Creates new form SetProxyGUI
     */
    public SetProxyGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        headingPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        hostnameLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        hostnameTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        proxyToggleButton = new javax.swing.JButton();
        firefoxRadioButton = new javax.swing.JRadioButton();
        chromeRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Set Proxy");

        headingPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mainLabel.setText("Set Proxy for JMeter v1.0. By James Snee. (c) 2016.");

        jLabel1.setText("Please ensure Firefox is closed before turning proxy on or off.");

        javax.swing.GroupLayout headingPanelLayout = new javax.swing.GroupLayout(headingPanel);
        headingPanel.setLayout(headingPanelLayout);
        headingPanelLayout.setHorizontalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingPanelLayout.createSequentialGroup()
                        .addComponent(mainLabel)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64))))
        );
        headingPanelLayout.setVerticalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        buttonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        hostnameLabel.setText("HostName:");

        portLabel.setText("Port:");

        proxyToggleButton.setText("Turn Proxy On!");
        proxyToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyToggleButtonActionPerformed(evt);
            }
        });

        radioButtonGroup.add(firefoxRadioButton);
        firefoxRadioButton.setSelected(true);
        firefoxRadioButton.setText("Firefox?");
        firefoxRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firefoxRadioButtonActionPerformed(evt);
            }
        });

        radioButtonGroup.add(chromeRadioButton);
        chromeRadioButton.setText("Chrome?");

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hostnameLabel)
                            .addComponent(portLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firefoxRadioButton)
                            .addComponent(chromeRadioButton)
                            .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hostnameTextField)
                                .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                        .addComponent(proxyToggleButton)
                        .addGap(164, 164, 164))))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostnameLabel)
                    .addComponent(hostnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(firefoxRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chromeRadioButton)
                .addGap(18, 18, 18)
                .addComponent(proxyToggleButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firefoxRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firefoxRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firefoxRadioButtonActionPerformed

    //Method to show an error dialog
    public void showErrorDialog(String name, String message){
        JOptionPane.showMessageDialog(this, message, name, JOptionPane.ERROR_MESSAGE);
    }
    
    
    private void proxyToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyToggleButtonActionPerformed
        
        String hostnameRe = "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})";
        String portRe = "(\\d)";
        String hostname = this.hostnameTextField.getText();
        String port = this.portTextField.getText();
        
        //check values inside text fields - validation
        //invalid
        if(!hostname.isEmpty()){
            if(!hostname.matches(hostnameRe)){
                showErrorDialog("Error!", "Error: Formatting wrong. Format is: xxx.xxx.xxx.xxx");
                System.out.println("Error: Formatting wrong. Format is: xxx.xxx.xxx.xxx");
            }
            //valid
            else {
                //send variables to AppData
                AppData.getInstance().setHostName(hostname);
                //check port
                if(!port.isEmpty()){
                   
                    if(AppData.getInstance().isAlpha(port)){
                        showErrorDialog("Error!", "Error: port can only be numeric!");
                        System.out.println("Error: port can only be numeric!");
                    }
                    //valid
                    else {
                        //check length is 5 characters
                        if(port.length() > 5){
                            showErrorDialog("Error!", "Error: Input too long! Ensure port number is 5 characters.");
                        }
                        else {
                            //send variables to AppData
                            AppData.getInstance().setPort(portTextField.getText());
                        }
   
                    }
                    
                }
                else {
                    showErrorDialog("Error!", "Error: Port value cannot be empty!");
                    System.out.println("Error: Port value cannot be empty!");
                }
            }
        }
        else {
            showErrorDialog("Error!", "Error: Hostname value cannot be empty!");
            System.out.println("Error: Hostname value cannot be empty!");
        }
        
        //Once validation is done, we can perform action
        boolean proxyCheck = AppData.getInstance().isProxyCheck();
        //if proxyCheck is true, turn off proxy
        if(proxyCheck){
            AppData.getInstance().turnOffProxy();
        }
        //otherwise, turn on proxy
        else {
             try{
                 AppData.getInstance().turnOnProxy(AppData.getInstance().getHostName(), AppData.getInstance().getPort());
             }
             catch(IOException e){}
             
        }
        
        
    }//GEN-LAST:event_proxyToggleButtonActionPerformed

    public JTextField getHostnameTextField() {
        return hostnameTextField;
    }

    public void setHostnameTextField(JTextField hostnameTextField) {
        this.hostnameTextField = hostnameTextField;
    }

    public JTextField getPortTextField() {
        return portTextField;
    }

    public void setPortTextField(JTextField portTextField) {
        this.portTextField = portTextField;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JRadioButton chromeRadioButton;
    private javax.swing.JRadioButton firefoxRadioButton;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JLabel hostnameLabel;
    private javax.swing.JTextField hostnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton proxyToggleButton;
    private javax.swing.ButtonGroup radioButtonGroup;
    // End of variables declaration//GEN-END:variables
}
